import { type Metadata } from "next";
import { DM_Sans } from "next/font/google";

import "@/assets/css/globals.css";
import Providers from "@/components/providers";
import { cn } from "@/lib/utils";

const dmSans = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Coeus",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={cn("antialiased", dmSans.className)}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
